// Autogenerated by Frugal Compiler (2.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

pub const REDEF_CONST: i32 = rust::CONST_I32_FROM_BASE;

pub const CONST_THING: rust::Thing = rust::Thing {
    an_id: 1,
    a_string: "some string".into(),
};

pub const DEFAULT_ID: Id = -1;

pub const OTHER_DEFAULT: Id = DEFAULT_ID;

pub const THIRTYFOUR: i8 = 34;
