[package]
name = "rust"
version = "2.22.0"

[dependencies]
frugal = { path = "../../../lib/rust" }
futures = "0.1"
lazy_static = "1.2"
log = "0.4"
nats = "0.3"
thrift = { path = "/home/tanner/code/thrift/lib/rs" }
tower-service = "0.1"
tower-web = "0.3"
