// Autogenerated by Frugal Compiler (2.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

use super::*;

pub trait FBaseFoo {
    fn basePing(ctx: FContext) -> thrift::Result<()>;
}
