// Autogenerated by Frugal Compiler (2.23.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(unused_variables)]

use std::collections::BTreeMap;
use std::error::Error;

use futures::future::{self, FutureResult};
use futures::{Async, Future, Poll};
use thrift;
use thrift::protocol::{TInputProtocol, TOutputProtocol};
use thrift::transport::{TReadTransport, TWriteTransport};
use tower_service::Service;
use tower_web::middleware::{self, Middleware};
use tower_web::util::Chain;

use frugal::buffer::FMemoryOutputBuffer;
use frugal::context::FContext;
use frugal::errors;
use frugal::processor::FProcessor;
use frugal::protocol::{
    FInputProtocol, FInputProtocolFactory, FOutputProtocol, FOutputProtocolFactory,
};
use frugal::provider::FServiceProvider;
use frugal::service::example;
use frugal::service::Request;
use frugal::transport::FTransport;

pub trait FBaseFoo {
    fn base_ping(&mut self, ctx: &FContext) -> thrift::Result<()>;
}

pub struct FBaseFooClient<S>
where
    S: Service<Request = FBaseFooRequest, Response = FBaseFooResponse, Error = thrift::Error>,
{
    service: S,
}

impl<T> FBaseFooClient<FBaseFooClientService<T>>
where
    T: FTransport,
{
    pub fn new(provider: FServiceProvider<T>) -> FBaseFooClient<FBaseFooClientService<T>> {
        FBaseFooClient {
            service: FBaseFooClientService {
                transport: provider.transport,
                input_protocol_factory: provider.input_protocol_factory,
                output_protocol_factory: provider.output_protocol_factory,
            },
        }
    }
}

impl<S> FBaseFoo for FBaseFooClient<S>
where
    S: Service<Request = FBaseFooRequest, Response = FBaseFooResponse, Error = thrift::Error>,
{
    fn base_ping(&mut self, ctx: &FContext) -> thrift::Result<()> {
        let request = FBaseFooRequest::new(
            ctx.clone(),
            FBaseFooMethod::BasePing(FBaseFooPingArgs::new()),
        );
        match self.service.call(request).wait()? {
            FBaseFooResponse::BasePing(_) => (),
            // TODO: See if we can detect and avoid generating this branch
            _ => panic!("FBaseFooClient::base_ping() recieved an incorrect response"),
        };
        Ok(())
    }
}

pub struct FBaseFooClientService<T>
where
    T: FTransport,
{
    transport: T,
    input_protocol_factory: FInputProtocolFactory,
    output_protocol_factory: FOutputProtocolFactory,
}

impl<T> FBaseFooClientService<T>
where
    T: FTransport,
{
    fn call_delegate(&mut self, req: FBaseFooRequest) -> Result<FBaseFooResponse, thrift::Error> {
        let FBaseFooRequest { mut ctx, method } = req;
        let mut buffer = FMemoryOutputBuffer::new(0);
        {
            let mut oprot = self.output_protocol_factory.get_protocol(&mut buffer);
            oprot.write_request_header(&ctx)?;
            let mut oproxy = oprot.t_protocol_proxy();
            match method {
                FBaseFooMethod::BasePing(args) => {
                    oproxy.write_message_begin(&thrift::protocol::TMessageIdentifier {
                        name: "basePing".into(),
                        message_type: thrift::protocol::TMessageType::Call,
                        sequence_number: 0,
                    })?;
                    let args = FBaseFooPingArgs {};
                    args.write(&mut oproxy)?;
                }
            };
            oproxy.write_message_end()?;
            oproxy.flush()?;
        }
        let mut result_transport = self.transport.request(&ctx, buffer.bytes())?;
        {
            let mut iprot = self
                .input_protocol_factory
                .get_protocol(&mut result_transport);
            iprot.read_response_header(&mut ctx)?;
            let mut iproxy = iprot.t_protocol_proxy();
            let msg_id = iproxy.read_message_begin()?;
            if msg_id.name != "basePing" {
                return Err(thrift::new_application_error(
                    thrift::ApplicationErrorKind::WrongMethodName,
                    "basePing failed: wrong method name",
                ));
            }
            match msg_id.message_type {
                thrift::protocol::TMessageType::Exception => {
                    let err = thrift::Error::Application(
                        thrift::Error::read_application_error_from_in_protocol(&mut iproxy)?,
                    );
                    iproxy.read_message_end()?;
                    if frugal::errors::is_too_large_error(&err) {
                        Err(thrift::new_transport_error(
                            thrift::TransportErrorKind::SizeLimit,
                            err.to_string(),
                        ))
                    } else {
                        Err(err)
                    }
                }
                thrift::protocol::TMessageType::Reply => {
                    let mut result = FBaseFooPingResult::new();
                    result.read(&mut iproxy)?;
                    iproxy.read_message_end()?;
                    Ok(FBaseFooResponse::BasePing(result))
                }
                _ => Err(thrift::new_application_error(
                    thrift::ApplicationErrorKind::InvalidMessageType,
                    "basePing failed: invalid message type",
                )),
            }
        }
    }
}

impl<T> Service for FBaseFooClientService<T>
where
    T: FTransport,
{
    type Request = FBaseFooRequest;
    type Response = FBaseFooResponse;
    type Error = thrift::Error;
    type Future = FutureResult<Self::Response, Self::Error>;

    fn poll_ready(&mut self) -> Poll<(), thrift::Error> {
        Ok(Async::Ready(()))
    }

    fn call(&mut self, req: FBaseFooRequest) -> FutureResult<FBaseFooResponse, thrift::Error> {
        self.call_delegate(req).into()
    }
}

pub struct FBaseFooPingArgs {}

impl FBaseFooPingArgs {
    pub fn new() -> FBaseFooPingArgs {
        FBaseFooPingArgs {}
    }

    fn read<R, T>(&mut self, iprot: &mut T) -> thrift::Result<()>
    where
        R: thrift::transport::TReadTransport,
        T: thrift::protocol::TInputProtocol<R>,
    {
        iprot.read_struct_begin()?;
        loop {
            let field_id = iprot.read_field_begin()?;
            if field_id.field_type == thrift::protocol::TType::Stop {
                break;
            };
            match field_id.id {
                _ => iprot.skip(field_id.field_type)?,
            };
            iprot.read_field_end()?;
        }
        iprot.read_struct_end()
    }

    fn write<W, T>(&self, oprot: &mut T) -> thrift::Result<()>
    where
        W: TWriteTransport,
        T: TOutputProtocol<W>,
    {
        oprot.write_struct_begin(&thrift::protocol::TStructIdentifier::new("basePing_args"))?;
        oprot.write_field_stop()?;
        oprot.write_struct_end()
    }
}

pub struct FBaseFooPingResult {}

impl FBaseFooPingResult {
    pub fn new() -> FBaseFooPingResult {
        FBaseFooPingResult {}
    }

    fn read<R, T>(&mut self, iprot: &mut T) -> thrift::Result<()>
    where
        R: thrift::transport::TReadTransport,
        T: thrift::protocol::TInputProtocol<R>,
    {
        iprot.read_struct_begin()?;
        loop {
            let field_id = iprot.read_field_begin()?;
            if field_id.field_type == thrift::protocol::TType::Stop {
                break;
            };
            match field_id.id {
                _ => iprot.skip(field_id.field_type)?,
            };
            iprot.read_field_end()?;
        }
        iprot.read_struct_end()
    }

    fn write<W, T>(&self, oprot: &mut T) -> thrift::Result<()>
    where
        W: TWriteTransport,
        T: TOutputProtocol<W>,
    {
        oprot.write_struct_begin(&thrift::protocol::TStructIdentifier::new("basePing_result"))?;
        oprot.write_field_stop()?;
        oprot.write_struct_end()
    }
}

pub struct FBaseFooProcessor<S>
where
    S: Service<Request = FBaseFooRequest, Response = FBaseFooResponse, Error = thrift::Error>,
{
    service: S,
}

pub struct FBaseFooProcessorBuilder<F, M>
where
    F: FBaseFoo,
{
    handler: F,
    middleware: M,
}

impl<F> FBaseFooProcessorBuilder<F, middleware::Identity>
where
    F: FBaseFoo,
{
    pub fn new(handler: F) -> Self {
        FBaseFooProcessorBuilder {
            handler,
            middleware: middleware::Identity::new(),
        }
    }
}

impl<F, M> FBaseFooProcessorBuilder<F, M>
where
    F: FBaseFoo,
{
    pub fn middleware<U>(
        self,
        middleware: U,
    ) -> FBaseFooProcessorBuilder<F, <M as Chain<U>>::Output>
    where
        M: Chain<U>,
    {
        FBaseFooProcessorBuilder {
            handler: self.handler,
            middleware: self.middleware.chain(middleware),
        }
    }

    pub fn build(self) -> FBaseFooProcessor<M::Service>
    where
        M: Middleware<
            FBaseFooProcessorService<F>,
            Request = FBaseFooRequest,
            Response = FBaseFooResponse,
            Error = thrift::Error,
        >,
    {
        FBaseFooProcessor {
            service: self.middleware.wrap(FBaseFooProcessorService(self.handler)),
        }
    }
}

pub struct FBaseFooRequest {
    ctx: FContext,
    method: FBaseFooMethod,
}

impl FBaseFooRequest {
    pub fn new(ctx: FContext, method: FBaseFooMethod) -> FBaseFooRequest {
        FBaseFooRequest { ctx, method }
    }
}

impl Request for FBaseFooRequest {
    fn context(&mut self) -> &mut FContext {
        &mut self.ctx
    }

    fn method_name(&self) -> &'static str {
        match self.method {
            FBaseFooMethod::BasePing(_) => "basePing",
        }
    }
}

pub enum FBaseFooMethod {
    BasePing(FBaseFooPingArgs),
}

pub enum FBaseFooResponse {
    BasePing(FBaseFooPingResult),
}

pub struct FBaseFooProcessorService<F: FBaseFoo>(F);

impl<F> Service for FBaseFooProcessorService<F>
where
    F: FBaseFoo,
{
    type Request = FBaseFooRequest;
    type Response = FBaseFooResponse;
    type Error = thrift::Error;
    type Future = FutureResult<Self::Response, Self::Error>;

    fn poll_ready(&mut self) -> Poll<(), thrift::Error> {
        Ok(Async::Ready(()))
    }

    fn call(&mut self, req: FBaseFooRequest) -> FutureResult<FBaseFooResponse, thrift::Error> {
        let result = match req.method {
            FBaseFooMethod::BasePing(args) => self
                .0
                .base_ping(&req.ctx)
                .map(|res| FBaseFooResponse::BasePing(FBaseFooPingResult {})),
        };
        future::result(result)
    }
}

impl<S> FProcessor for FBaseFooProcessor<S>
where
    S: Service<Request = FBaseFooRequest, Response = FBaseFooResponse, Error = thrift::Error>,
{
    fn process<R, W>(
        &mut self,
        iprot: &mut FInputProtocol<R>,
        oprot: &mut FOutputProtocol<W>,
    ) -> thrift::Result<()>
    where
        R: TReadTransport,
        W: TWriteTransport,
    {
        let ctx = iprot.read_request_header()?;
        let name = {
            let mut iproxy = iprot.t_protocol_proxy();
            iproxy.read_message_begin().map(|tmid| tmid.name)?
        };

        match &*name {
            "basePing" => self.base_ping(&ctx, iprot, oprot),
            _ => {
                error!(
                    "frugal: client invoked unknown function {} on request with correlation id {}",
                    &name,
                    ctx.correlation_id()
                );
                let mut iproxy = iprot.t_protocol_proxy();
                iproxy.skip(thrift::protocol::TType::Struct)?;
                iproxy.read_message_end()?;

                oprot.write_response_header(&ctx)?;
                let mut oproxy = oprot.t_protocol_proxy();
                oproxy.write_message_begin(&thrift::protocol::TMessageIdentifier::new(
                    &name as &str,
                    thrift::protocol::TMessageType::Exception,
                    0,
                ))?;
                let ex = thrift::ApplicationError::new(
                    thrift::ApplicationErrorKind::UnknownMethod,
                    format!("Unknown function {}", &name),
                );
                thrift::Error::write_application_error_to_out_protocol(&ex, &mut oproxy)?;
                oproxy.write_message_end()?;
                oproxy.flush()
            }
        }
    }
}

impl<S> FBaseFooProcessor<S>
where
    S: Service<Request = FBaseFooRequest, Response = FBaseFooResponse, Error = thrift::Error>,
{
    fn base_ping<R, W>(
        &mut self,
        ctx: &FContext,
        iprot: &mut FInputProtocol<R>,
        oprot: &mut FOutputProtocol<W>,
    ) -> thrift::Result<()>
    where
        R: TReadTransport,
        W: TWriteTransport,
    {
        let mut args = FBaseFooPingArgs {};
        let mut iproxy = iprot.t_protocol_proxy();
        args.read(&mut iproxy)?;
        iproxy.read_message_end()?;
        let req = FBaseFooRequest {
            ctx: ctx.clone(),
            method: FBaseFooMethod::BasePing(args),
        };
        match self.service.call(req).wait() {
            Err(thrift::Error::User(err)) => {
                error!(
                    "{} {}: {}",
                    errors::USER_ERROR_DESCRIPTION,
                    ctx.correlation_id(),
                    err.description()
                );
                Ok(())
            }
            Err(err) => {
                error!(
                    "{} {}: {}",
                    errors::USER_ERROR_DESCRIPTION,
                    ctx.correlation_id(),
                    err.description()
                );
                Ok(())
            }
            Ok(response) => {
                let write_result = oprot
                    .write_response_header(&ctx)
                    .and_then(|()| {
                        oprot.t_protocol_proxy().write_message_begin(
                            &thrift::protocol::TMessageIdentifier::new(
                                "basePing",
                                thrift::protocol::TMessageType::Reply,
                                0,
                            ),
                        )
                    }).and_then(|()| {
                        let result = FBaseFooPingResult {};
                        result.write(&mut oprot.t_protocol_proxy())
                    }).and_then(|()| oprot.t_protocol_proxy().write_message_end())
                    .and_then(|()| oprot.t_protocol_proxy().flush());

                match write_result {
                    Err(err) => {
                        if errors::is_too_large_error(&err) {
                            errors::write_application_error(
                                "basePing",
                                &ctx,
                                &thrift::ApplicationError::new(
                                    thrift::ApplicationErrorKind::Unknown,
                                    errors::APPLICATION_EXCEPTION_RESPONSE_TOO_LARGE,
                                ),
                                oprot,
                            )
                        } else {
                            Err(err)
                        }
                    }
                    Ok(_) => Ok(()),
                }
            }
        }
    }
}
