// Autogenerated by Frugal Compiler (2.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

use super::*;

pub trait FBaseFoo {
    fn base_ping(ctx: FContext) -> thrift::Result<()>;
}
